### ISSUE TITLE
Add tags to post

### ISSUE THREAD

**Issue by ZenixReal** [nextcord/nextcord#1056]
### Summary

Add tags to post

### Reproduction Steps

1. Create a Cog
2. Call an event ('on_thread_join')
3. Check Member and Channel ID
4. Edit thread

### Minimal Reproducible Code

```python
@commands.Cog.listener('on_thread_join')
async def on_thread_join(self, thread: nextcord.Thread) -> None:
    if thread.owner.bot: return
    galaryChannel = thread.guild.get_channel(1085690392994906203)
    Karo = thread.guild.get_member(839908473424183366)
    if thread.parent.id == galaryChannel.id:
        if thread.owner.id == Karo.id:
            tagList = [nextcord.ForumTag(name="Verifiziert"), nextcord.ForumTag(name="Populär")]
            await thread.edit(applied_tags=tagList)
```

### Expected Results

I expected the bot to add 2 different ForumTags in a post when a specific user creates a post in a forum channel.

### Actual Results

There was an error in the console that made me very suspicious.

Error code:
```python
nextcord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In applied_tags.0: This field is required
In applied_tags.1: This field is required
```

Traceback:
```py
Ignoring exception in on_thread_join
Traceback (most recent call last):
  File "C:\Users\tati\AppData\Roaming\Python\Python311\site-packages\nextcord\client.py", line 490, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\tati\Desktop\Bots\Meine Projekte\Yacht Manager\extensions\automatic.py", line 31, in on_thread_join
    await thread.edit(applied_tags=tagList)
  File "C:\Users\tati\AppData\Roaming\Python\Python311\site-packages\nextcord\threads.py", line 648, in edit
    data = await self._state.http.edit_channel(self.id, **payload)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tati\AppData\Roaming\Python\Python311\site-packages\nextcord\http.py", line 400, in request
    raise HTTPException(response, data)
```

### Intents

I have all intents active. (nextcord.Intents.all())

### System Information

- Python v3.11.1-final
- nextcord v2.4.0-final
- aiohttp v3.8.4
- system info: Windows 10 10.0.19045

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by kingmigdor** [comment]
You are not meant to edit the tags with the nextcord.ForumTag class. You should get the ForumTag's via [`Thread.parent`](https://docs.nextcord.dev/en/stable/api.html#nextcord.Thread.parent) (which should return the ForumChannel) and from there just [`ForumChannel.get_tag()`](https://docs.nextcord.dev/en/stable/api.html#nextcord.ForumChannel.get_tag).

Keep in mind that we are working with IDs here, as ForumTag's contain their own ID. If you want to get all available tags, you'd use [`ForumChannel.available_tags`](https://docs.nextcord.dev/en/stable/api.html#nextcord.ForumChannel.available_tags), also in order to get it from the ForumTag name.

Hope this answer helped you out!
