### ISSUE TITLE
Type nextcord.Embed method parameters more specifically

### ISSUE THREAD

**Issue by EmmmaTech** [nextcord/nextcord#1076]
### Summary

The methods for `nextcord.Embed` should have properly typed parameters.

### What is the feature request for?

The core library

### The Problem

Currently, many of the parameters in `nextcord.Embed` methods that are supposed to be `str` are typed with `Any`. This is not ideal because static type checkers will allow you to provide any object, whether it's appropriate for the method. It's like that so the parameters can support any object then be stringified later, but it could lead to weird problems if not used correctly.

Here's an example of this:
https://github.com/nextcord/nextcord/blob/dcadc7ea6d3e29c581cd49c2bbce3936a8804983/nextcord/embeds.py#L324

### The Ideal Solution

`nextcord.Embed` methods should be typed more precisely to only allow objects that support conversion to `str`. For example, in our example method `set_footer`, if an object that supports conversion to a string (`__str__`) is provided, then the type checker will be happy. Otherwise, it will throw an error.

This can be accomplished by typing the parameter with a protocol that lists the supported conversion method. Unfortunately, Python does not have a [built-in protocol](https://docs.python.org/3/library/typing.html#protocols) for conversion to a string because technically every object can be converted to a string. We will have to make our own. 

### Additional Context

As [discussed on the Discord Server](https://discord.com/channels/881118111967883295/881124672056467456/1125003163024502784), this issue will be for v3.

**Comment by Jodenee** [comment]
I'm not sure if a protocol would fit in this situation, as you know every class in python can be converted into a str with or without manually implementing the __str__ magic method as python will just default to __repr__ if __str__ is not implemented, and that's where the issue is. It's impossible to tell if it is implemented or not with protocols as to protocols __str__ is always defined.

But I am aware of one way of achieving this, what we can do instead is make use of an ABC with just the __str__ magic method as an abstract method, but this comes with its own drawbacks such as, forcing the ABC to be inherited by the user's classes and it not supporting literal strings, so the typing would need to be a union of the ABC and str.

If you are fine with me using the above method, I wouldn't mind submitting a pr to resolve your issue.

**Comment by Jodenee** [comment]
Forgot to mention this in my last message but the user wont be able to pass raw numbers and such as arguments. So they'll need to convert those values into strings using `str()`. This is because primitive types don't inherit the ABC so the type checker wont know if `__str__` is implemented or not, just thought that was worth mentioning in case this isn't the solution you wanted.

If you're fine with that, feel free to assign me to this issue. I'm down to implement it.
