### ISSUE TITLE
Implement DiscoveryMetadata

### ISSUE THREAD

**Issue by sairam4123** [nextcord/nextcord#114]
### Link

https://github.com/Rapptz/discord.py/pull/6887

**Comment by ooliver1** [comment]
Discord has decided to leave this undocumented, we usually do not implement undocumented features due to instability from a lack of guarantee of breaking changes (which recently they have not cared about but that is out of the scope of this), so I will be closing this issue.

discord/discord-api-docs#1762
> Thanks for the pull request. As this has been open/inactive since 2020, I think it's safe to say we're going to leave this undocumented for the time being. Feel free to move this over to a feature request under the Discussions section if you have an interesting use case for this data.

I do not agree with this decision by night but it will have to do.
