### ISSUE TITLE
Add warning for more than 50 slash commandy

### ISSUE THREAD

**Issue by HumanBot000** [nextcord/nextcord#1141]
### Summary

Discord only allows 59 Slash commands per application.It would be nice to get a error from the libary it you register more than 50.So you don't sit there and wait why DC don't register your new commands

### What is the feature request for?

Application commands

### The Problem

As mentioned in summary
Btw this limit is dumb but I think you can't do much about it.

### The Ideal Solution

Raise ToManyCommandsError when running bot.run

### The Current Solution

Nothing discord just don't register your commands

**Comment by Soheab** [comment]
Not sure where you got the random number 59 but it's 100 globally and per guild as the [API Docs](https://discord.com/developers/docs/interactions/application-commands#registering-a-command) mention. The API does also throw a [specific error](https://discord.com/developers/docs/topics/opcodes-and-status-codes#:~:text=has%20a%20template-,30032,-Maximum%20number%20of) if the limit is reached, not sure how the library handles that though.

Having said that, I don't think the library should set a hard limit since Discord can change it any time, users should be aware of the limit.

**Comment by ooliver1** [comment]
Generally we don't add validation for limits like this. It is quite rare to meet the limit as that is on top level commands. You can have 25 sub command groups with 25 sub commands each, coming to 62500 sub commands - where you're limited by the size of the slash command payload itself.

**Comment by HumanBot000** [comment]
Typo 50 is the limit,I am really sure

**Comment by ooliver1** [comment]
No. The limit is 100 as shown in the first link.

**Comment by HumanBot000** [comment]
https://github.com/discord/discord-api-docs/issues/2312

Oliver Wilkes ***@***.***> schrieb am Mi., 25. Okt. 2023,
13:58:

**Comment by ooliver1** [comment]
A discussion is not the correct place to get information. Soheab linked the [__**Discord Documentation Page**__](https://discord.com/developers/docs/interactions/application-commands#registering-a-command) which says 100 `CHAT_INPUT` commands.
