### ISSUE TITLE
Custom_Id in interaction

### ISSUE THREAD

**Issue by lordcod** [nextcord/nextcord#1143]
### Summary

 in the next update, add custom_id to the interaction, yes, it can be found in data, and still it will be more convenient

### What is the feature request for?

Application commands

### The Problem

It will be easier to find out the custom_id from the interaction

### The Ideal Solution

add to the interaction property custom_id class which will be obtained from data

**Comment by spifory** [comment]
There doesn't seem to be a `custom_id` documented under Interaction/Interaction data under Discord's documentation.
I could only find an `id` that existed under Interaction, and a `custom_id` under _component_ (modals, buttons, ...) interactions (which exist in nextcord)

**Comment by lordcod** [comment]
> There doesn't seem to be a `custom_id` documented under Interaction/Interaction data under Discord's documentation. I could only find an `id` that existed under Interaction, and a `custom_id` under _components_ (modals, buttons, ...), which already exist in nextcord

there is interaction.data there is a dict issued in which there is a custom_id

**Comment by Soheab** [comment]
I don't see why this is needed and you didn't provide any use case either.

`custom_id` is an attribute on all subclasses of `Item` so it should already be accessible?
If this is for the `on_interaction` event then we don't really recommend using that over the callbacks.

**Comment by lordcod** [comment]
> I don't see why this is needed and you didn't provide any use case either.
> 
> `custom_id` is an attribute on all subclasses of `Item` so it should already be accessible? If this is for the `on_interaction` event then we don't really recommend using that over the callbacks.

this parameter can be added to button, dropdown exactly and in on_interaction to find out the custom_id and use, for example, for inactive interaction

**Comment by Soheab** [comment]
> > I don't see why this is needed and you didn't provide any use case either.
> > 
> > `custom_id` is an attribute on all subclasses of `Item` so it should already be accessible? If this is for the `on_interaction` event then we don't really recommend using that over the callbacks.
> 
> this parameter can be added to button, dropdown exactly and in on_interaction to find out the custom_id and use, for example, for inactive interaction 

Thought so. The library provides something called ["Persistent View"](https://github.com/nextcord/nextcord/blob/master/examples/views/persistent.py) for that case. As I said, we don't recommend using the event, there is even a warning on the [docs](https://docs.nextcord.dev/en/stable/api.html#nextcord.on_interaction) about it.
![good-file-name.jpg](https://github.com/nextcord/nextcord/assets/33902984/9484e98a-3ddf-4693-bd61-bda5af8dd408)

Having said that.. our (NC maintainers) stance on that may change for v3 since the warning and all are from discord.py 🤷

**Comment by EmreTech** [comment]
Since all view items include a `custom_id` attribute already, there's no use in having a `custom_id` attribute in the interaction class. If you absolutely need it from the interaction object for some reason, you can get it from [`Interaction.data`](https://docs.nextcord.dev/en/stable/api.html#nextcord.Interaction.data).
