### ISSUE TITLE
Buttons move when refreshing

### ISSUE THREAD

**Issue by onerandomusername** [nextcord/nextcord#331]
### Summary

views are not of prime production material

### Reproduction Steps

Used one. 

### Minimal Reproducible Code

```python
https://github.com/onerandomusername/test-bot/blob/nextcord-view-button-jump/bot/cogs/view.py
```

### Expected Results

views work as intended

### Actual Results

buttons move!

### Intents

irrelevant

### System Information

irrelevant

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

### Additional Context

I will attempt to fix this, context in nextcord guild.
https://canary.discord.com/channels/881118111967883295/881118112492191796/928222740333330503

**Comment by TAG-Epic** [comment]
While views need to be refactored, this will instead happen in v3 instead of v2. The bug however should be fixed in v2 aswell.

**Comment by DenverCoder1** [comment]
Danny had a solution

https://github.com/Rapptz/discord.py/commit/e198a0e7e6df58bdfcba1cdbf31345ed67c5f10e

> Avoid re-creating View children on edit
>     
> The older code attempted to be clever and sync component additions and
removals with what the message edit is doing. In some cases, this led
to the re-creation of those components causing lost attributes to be
dropped such as `_rendered_row` which would mess up handling of view
weights.
>     
> Instead of recreating the children list every time and keeping track
of additions and removals, this change just updates the old state with
the new state while ignoring any new or removed additions. This should
work fine in theory due to additions or removals already being present
before editing the View instance in the first place.
