### ISSUE TITLE
Nextcord.Message.view(s)

### ISSUE THREAD

**Issue by TheOriginalSoni** [nextcord/nextcord#522]
### Summary

An attribute that returns a list of views currently on the message

### What is the feature request for?

nextcord.ext.commands

### The Problem

`Nextcord.Message.edit(view=$SomeView)` allows us to edit views. However, there is no current ways to get views.

### The Ideal Solution

A new attribute

**Comment by plun1331** [comment]
You can use `View.from_message`

**Comment by DenverCoder1** [comment]
_Just copying my comments from Discord for future people who may come across this:_

Discord doesn't really support that since views are Python classes that map components to callbacks

Discord only really knows about the components, not the views

So you can ask Discord for the components in the message with [`message.components`](https://nextcord.readthedocs.io/en/stable/api.html?highlight=view%20from#nextcord.Message.components), but that's not all you need since they won't be associated with your callback functions so it doesn't really help

BUT, you can write logic that maps the components to the correct callbacks

It takes some careful planning to do it, but you can make a View subclass that can take in component payloads Discord gives you, and create the necessary instantiated Components with callbacks from them

There's also the nextcord function [`View.from_message`](https://nextcord.readthedocs.io/en/stable/api.html?highlight=view%20from#nextcord.ui.View.from_message) that can convert the message components into a View, but it will be a new View instance each time without state and won't automatically map to callbacks (unless the bot is already associating the callbacks with the button ids or they appear in a persistent view with custom_ids). As you may have additional context to your View subclass, this is often not good enough.

From my understanding of how things work behind the scenes, Nextcord can't provide a simpler approach than it already has.

Restoring a view to the necessary state depends entirely on the specific use case and View implementation and will normally have to be done manually by the bot developer (in situations where `View.from_message` isn't enough)

**Comment by ooliver1** [comment]
in short, views are stateful, components can be taken from messages and used with view but shouldnt be constructed per view
