### ISSUE TITLE
`Union` for slash option channels

### ISSUE THREAD

**Issue by ooliver1** [nextcord/nextcord#591]

**Comment by DenverCoder1** [comment]
> `nextcord.Range[min, max]` - unsure how min or max only will work and if thats possible anyway

The way this is proposed, I don't believe it can be implemented since the args of a type must be types, not ints or floats, etc.

Python also does not like runtime checks in type annotations (eg. `arg: Range(min, max)`)

What can potentially be done however, is typing with `typing_extensions.Annotated`, for example:

```py
arg: Annotated[int, Range(1, 10)])
```

This will tell Python to use it as an int for typing purposes, but use Range(1, 10) as a runtime use or validation.

See https://peps.python.org/pep-0593/

**Comment by ooliver1** [comment]
> > `nextcord.Range[min, max]` - unsure how min or max only will work and if thats possible anyway
> 
> The way this is proposed, I don't believe it can be implemented since the args of a type must be types, not ints or floats, etc.
> 
> Python also does not like runtime checks in type annotations (eg. `arg: Range(min, max)`)
> 
> What can potentially be done however, is typing with `typing_extensions.Annotated`, for example:
> 
> ```python
> arg: Annotated[int, Range(1, 10)])
> ```
> 
> This will tell Python to use it as an int for typing purposes, but use Range(1, 10) as a runtime use or validation.
> 
> See https://peps.python.org/pep-0593/

typing.Literal is an example of objects used as the generic args
annotated would be good though, i was taking inspiration off discord.py slash_utils by maya

annotated sounds much better for that
