### ISSUE TITLE
`on_application_command_error` throwing to console even when a handler exists

### ISSUE THREAD

**Issue by ooliver1** [nextcord/nextcord#634]
### Summary

application errors will always show in console no matter if they are handled or not

### Reproduction Steps

1. make an `on_application_command_error` cog listener
2. make a command raise
3. observe it in console (not same as `ext.commands`' `on_command_error`

### Minimal Reproducible Code

```python
from nextcord.ext.commands import Cog


class MyCog(Cog):
    def __init__(self, *_):
        ...

    @Cog.listener()
    async def on_application_command_error(*_):
        ...


def setup(bot):
    bot.add_cog(MyCog(bot))
```

### Expected Results

The error not to be shown to console like `ext.commands` does.

### Actual Results

Error thrown to console no matter what.

### Intents

N/A

### System Information

nextcord 2.0.0a10
rest is irrelevant

### Checklist

- [X] I have searched the open issues for duplicates.
- [X] I have shown the entire traceback, if possible.
- [X] I have removed my token from display, if visible.

**Comment by Skelmis** [comment]
This is expected behavior, atleast based on how events vs listeners should work conceptually. This issue actually appears to show that ext.commands is bugged.

Registering an event with `@bot.event` overrides the event with a new handler, so the previous handler does not get called.

Registering a listener should *not* override the original handler, it simply adds another method to be called when the event runs. I.e. listen
This form of system allows for multiple listeners on single events, and a prevalent example would be adding an `on_ready` to every cog.
