### ISSUE TITLE
text to voice (ttv)

### ISSUE THREAD

**Issue by MaskDuck** [nextcord/nextcord#654]
### Summary

title

### What is the feature request for?

The core library

### The Problem

ttv is released

and it broke my bot
and my friends' bot
and sham's bot
and everyone's bot that's using nc

### The Ideal Solution

implement ttv

### The Current Solution

raising an error

### Additional Context

i wanna work on this

**Comment by Skelmis** [comment]
This issue provides little to no context for anyone who reads this.

Please add more context, this could be in the form of tracebacks, minimum reproducible code, etc

**Comment by MaskDuck** [comment]
i mean... its a **feature request**

im asking to implement ttv

**Comment by Skelmis** [comment]
Okay, well based on that information I don't see a couple things:
1) How not having built in text to speech broke everyones bots. All of mine appear to be working as expected.
2) Why nextcord should add some form of support built in for something like `gtts` or `pyttsx3`


If you *actually* meant this issue is about [this](https://support.discord.com/hc/en-us/articles/4412085582359) then you need to be far clearer, instead of simply stating everyones bot broke and that we should implement text to speech (Which is unrelated to what I assume you were trying to say)

**Comment by ooliver1** [comment]
As skelmis said, this issue is very unclear, the feature is named "text in voice" and you provided no info as to the discord documentation for it, what it even is or anything. Don't assume everyone on GitHub is on Discord 24/7.

**Comment by ooliver1** [comment]
Superseded by #655
