### ISSUE TITLE
new default help command

### ISSUE THREAD

**Issue by MaskDuck** [nextcord/nextcord#690]
### Summary

title

### What is the feature request for?

The core library

### The Problem

the right-now help command is not really good, its made when buttons isnt released

### The Ideal Solution

design a new default help command. maybe using an embed or button/dropdown?

**Comment by toolifelesstocode** [comment]
IMO, the help command isn't meant to be pretty or anything. As people can, and already customize them to whatever they want, you might find that people may like not something like an embed too much. Remember that nextcord is not meant to be doing everything for you, therefore, if you want a nicer help command, you can do just that, but that's just my opinion.

And also, if for instance, we did something like a command in each embed field, it wouldn't work if you have more than 25 commands, as that is the embed field limit due to discord's limitations.

**Comment by H4ckerxx44** [comment]
Given the fact, that example help commands will be an own [repo](https://github.com/nextcord/nextcord-ext-help-commands), I think this issue can be closed.
