### ISSUE TITLE
add some sort of was_deleted() boolean to the Message object to check of the message still Exists

### ISSUE THREAD

**Issue by JacktheDevel0per** [nextcord/nextcord#747]
### Summary

allow for msg.was_deleted() or msg.deleted() or msg .deleted

### What is the feature request for?

The core library

### The Problem

my bot requires knowing if a message it sent is deleted.

### The Ideal Solution

return true if the message still Exists

### The Current Solution

```py
            is_deleted = False
            try:
               _delcheck = await interaction.channel.fetch_message(msg.id)

            except Exception as e:
                is_deleted = True
```

### Additional Context

The "Current Solution" is barely tested and is very jank so this would be very helpful

**Comment by koala9712** [comment]
Sounds like a good idea, I can think of scenarios I'd like that instead of try except'ing it.

**Comment by DenverCoder1** [comment]
If you are caching messages (which is the default given the intent), the message should get removed automatically from cache when the message_delete event is received.

If the message was created while the bot was caching messages, it should work to simply check if `ctx._state._get_message(msg_id)`  (similarly can be done on an `Interaction`, `Message`, etc. that has `_state` instead of `ctx`). This does use undocumented attributes though, but does not require an API call.

If the message was created before the bot was started, or otherwise the bot did not have access when it was created, then it would need to fetch the message to check.

In my opinion, this seems like a very specific use case, and as this is not something the Discord API has an endpoint for, so I think it would make more sense for individual bot developers to add this to their bot on their own, for example, you can have some util functions and include something like:

```py
async def message_deleted(message: nextcord.Message) -> bool:
    if message._state._get_message(message.id) is not None:
        return False
    try:
        await message.channel.fetch_message(message.id)
        return False
    except nextcord.NotFound:
        return True
```

This can be implemented however you choose, it could even take a channel and message id rather than a Message object to make it even more flexible.

**Comment by EmreTech** [comment]
Why is this still open? Denver's comment seemed to resolve this issue

**Comment by JacktheDevel0per** [comment]
Seems I forgot to close this, sorry
